<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit profile</name>
   <tag></tag>
   <elementGuidId>b1d7dcc2-8dce-4aca-b291-37576c1a8f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c39dbf4-2c8d-4b61-b653-cac42f5da571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2858bacc-3b27-4e3a-b9af-a446566b21b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>046d0956-9de7-4891-9fad-a044a4689ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block js-profile-editable-edit-button</value>
      <webElementGuid>dadf45f8-c424-45f9-995d-bd3ed974e078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click</name>
      <type>Main</type>
      <value>{&quot;event_type&quot;:&quot;user_profile.click&quot;,&quot;payload&quot;:{&quot;profile_user_id&quot;:120522998,&quot;target&quot;:&quot;INLINE_EDIT_BUTTON&quot;,&quot;user_id&quot;:120522998,&quot;originating_url&quot;:&quot;https://github.com/sbvanyo&quot;}}</value>
      <webElementGuid>7ea31b00-b3e6-4d8d-b18e-7f6890010501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click-hmac</name>
      <type>Main</type>
      <value>61faf9e6104b06090493c700a1dcfdd429da1c9681047b713a25daa73bb9f5b3</value>
      <webElementGuid>c2151aa0-cb5d-4b76-824d-671d103750df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit profile</value>
      <webElementGuid>be0bb784-ee2f-48b4-b2cd-393ddd1538dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js-focus-visible&quot;]/body[@class=&quot;logged-in env-production page-responsive page-profile mine&quot;]/div[@class=&quot;logged-in env-production page-responsive page-profile mine&quot;]/div[@class=&quot;application-main&quot;]/main[1]/div[@class=&quot;container-xl px-3 px-md-4 px-lg-5 mt-2&quot;]/div[@class=&quot;Layout Layout--flowRow-until-md Layout--sidebarPosition-start Layout--sidebarPosition-flowRow-start&quot;]/div[@class=&quot;Layout-sidebar&quot;]/div[@class=&quot;h-card mt-5&quot;]/div[@class=&quot;js-profile-editable-replace&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;js-profile-editable-area d-flex flex-column d-md-block&quot;]/div[@class=&quot;mb-3&quot;]/button[@class=&quot;btn btn-block js-profile-editable-edit-button&quot;]</value>
      <webElementGuid>9a56e90c-8138-460f-bab3-7a08cdc88c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='button']</value>
      <webElementGuid>e619f260-8810-4cba-8372-28197ca7640b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Studying full-stack web development at Nashville Software School.'])[2]/following::button[1]</value>
      <webElementGuid>828889a3-7f8d-479a-9af2-a51c6bd510d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>18106cfd-ffef-4429-8d1e-74ab59f095f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit profile']/parent::*</value>
      <webElementGuid>f7b59eb9-602e-481e-9b57-b204cd0024be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>832cd164-b74c-4a5e-ae64-98b8997bfc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'button' and (text() = 'Edit profile' or . = 'Edit profile')]</value>
      <webElementGuid>e45c3558-1500-400c-ae18-26372b794d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
