<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pronouns_userprofile_company</name>
   <tag></tag>
   <elementGuidId>45faa4cd-707d-43de-bb41-c52ea7f1d6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user[profile_company]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user[profile_company]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75b13356-9cba-49e8-b398-a7df37a4e377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 form-control flex-auto input-sm</value>
      <webElementGuid>e5f4c6b2-9c38-4432-9db2-3ebac3352e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>37c6c3ee-336b-4986-83d3-9b17b9b7c3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>26197418-02f6-430b-95b0-0aa566e67126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[profile_company]</value>
      <webElementGuid>398c6340-bac1-4821-99ae-ff6846ae1596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js-focus-visible&quot;]/body[@class=&quot;logged-in env-production page-responsive page-profile mine&quot;]/div[@class=&quot;logged-in env-production page-responsive page-profile mine&quot;]/div[@class=&quot;application-main&quot;]/main[1]/div[@class=&quot;container-xl px-3 px-md-4 px-lg-5 mt-2&quot;]/div[@class=&quot;Layout Layout--flowRow-until-md Layout--sidebarPosition-start Layout--sidebarPosition-flowRow-start&quot;]/div[@class=&quot;Layout-sidebar&quot;]/div[@class=&quot;h-card mt-5&quot;]/div[@class=&quot;js-profile-editable-replace&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;flex-order-1 flex-md-order-none&quot;]/waiting-form[1]/form[@class=&quot;position-relative flex-auto js-profile-editable-form&quot;]/div[@class=&quot;color-fg-muted mt-2 d-flex flex-items-center&quot;]/input[@class=&quot;ml-2 form-control flex-auto input-sm&quot;]</value>
      <webElementGuid>d2af85bb-cee9-49f1-9042-487a924f1df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user[profile_company]']</value>
      <webElementGuid>0603b790-1cca-4229-89e5-e9e9526860e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b87ebc47-4ccb-43e3-a4a8-07d7e817d3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Company' and @name = 'user[profile_company]']</value>
      <webElementGuid>923e3be0-46f1-4037-960e-cd47e397a91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
