<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Studying full-stack web developmen_797c8a</name>
   <tag></tag>
   <elementGuidId>ba09720f-fd35-4cf5-9c5f-d532bf741eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='user_profile_bio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_profile_bio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb94a2c3-c387-4bed-8469-755fe71135b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control js-length-limited-input mb-1 width-full js-user-profile-bio-edit focus-visible</value>
      <webElementGuid>c740a3b9-5442-4c30-8d0e-2f40b517341c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_profile_bio</value>
      <webElementGuid>2abf6719-9dc8-40cb-97a2-7fef1997a04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[profile_bio]</value>
      <webElementGuid>e9ae6564-f5fd-4287-bbf5-be23b3845d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add a bio</value>
      <webElementGuid>199f8731-02fc-4b28-95bb-542db363864b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add a bio</value>
      <webElementGuid>9053f1ed-efb4-4637-aa28-d8cef020e313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7112c50e-0444-44d2-a862-a627160f507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-max-length</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>711b0505-a76f-47cb-b78e-e9261f6a4707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-warning-text</name>
      <type>Main</type>
      <value>{{remaining}} remaining</value>
      <webElementGuid>cc0f7e28-37b2-4b17-bc62-2cc11d608544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Studying full-stack web development at Nashville Software School.</value>
      <webElementGuid>acf34268-13c0-4ffb-adc8-554acf36885a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_profile_bio&quot;)</value>
      <webElementGuid>93a68865-9a9b-44b8-93dc-778dc8499767</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='user_profile_bio']</value>
      <webElementGuid>c1d9e03e-eab6-40e0-b6ab-eff98c9b2678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bio'])[1]/following::textarea[1]</value>
      <webElementGuid>a894f6b9-fa74-442c-a794-0e5fd559f5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::textarea[1]</value>
      <webElementGuid>47ce2173-04a1-4e10-9b57-80c4727c2200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@mention'])[1]/preceding::textarea[1]</value>
      <webElementGuid>115115d0-03fa-4635-b57d-759b8c7abfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pronouns'])[1]/preceding::textarea[1]</value>
      <webElementGuid>18e14f71-cfb4-4423-a936-6b4f0dde382f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Studying full-stack web development at Nashville Software School.']/parent::*</value>
      <webElementGuid>aecb93cc-30f5-4ff6-97fd-a363021a00d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//text-expander/textarea</value>
      <webElementGuid>71e6f26c-34cc-469e-a281-8619047a9d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'user_profile_bio' and @name = 'user[profile_bio]' and @placeholder = 'Add a bio' and (text() = 'Studying full-stack web development at Nashville Software School.' or . = 'Studying full-stack web development at Nashville Software School.')]</value>
      <webElementGuid>9dba7fae-9056-4cbe-bcc8-899b07bf6607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
