<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create new_avatar circle</name>
   <tag></tag>
   <elementGuidId>c1d7f831-bc45-45d0-9614-5710ab4c4694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://avatars.githubusercontent.com/u/120522998?v=4')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.avatar.circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5067652-344a-47f2-a3e3-04c73bf795f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/120522998?v=4</value>
      <webElementGuid>05229274-d1f4-468f-9916-aedd9daee5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>27c28d6d-14a3-405a-930b-8b43bd9bd02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>b1299ae6-b3c6-4d8b-8257-0881a55b376b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>fe860b9f-7211-492a-9327-904c67782635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-component</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4ac71a4-5287-4dff-a9c1-a99ff0895333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar circle</value>
      <webElementGuid>ab9e7856-e569-4492-8697-08ca887c1e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js-focus-visible&quot;]/body[@class=&quot;logged-in env-production page-responsive full-width&quot;]/div[@class=&quot;logged-in env-production page-responsive full-width&quot;]/div[@class=&quot;position-relative header-wrapper js-header-wrapper&quot;]/header[@class=&quot;AppHeader&quot;]/div[@class=&quot;AppHeader-globalBar  js-global-bar&quot;]/div[@class=&quot;AppHeader-globalBar-end&quot;]/div[@class=&quot;AppHeader-user&quot;]/deferred-side-panel[1]/include-fragment[1]/react-partial-anchor[1]/button[@class=&quot;Button--invisible Button--medium Button Button--invisible-noVisuals color-bg-transparent p-0&quot;]/span[@class=&quot;Button-content&quot;]/span[@class=&quot;Button-label&quot;]/img[@class=&quot;avatar circle&quot;]</value>
      <webElementGuid>ae8b8951-90d8-4e10-9f61-c2270959eb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://avatars.githubusercontent.com/u/120522998?v=4')]</value>
      <webElementGuid>e8147485-5d06-4665-a64a-3c9b1d1cc77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d6ac80a5-5052-456b-b3fa-9d785caa0b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://avatars.githubusercontent.com/u/120522998?v=4']</value>
      <webElementGuid>cb9c4a1c-ac0f-47e5-9b03-35955df7e10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
